
version: "3"
services:

    mysql:
      image: mysql:5.7
      container_name: docker-symfony4-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./docker_dev/mysql/storage:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8002:3306"

    webserver:
      image: nginx:1.12.0
      container_name: docker-symfony4-webserver
      volumes:
        - .:/application
        - ./docker_dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      working_dir: /application      
      ports:
       - "8000:80"

    php:
      build: docker/php-fpm
      container_name: docker-symfony4-php-fpm
      volumes:
        - .:/application
        - ./docker_dev/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      working_dir: /application      

