version: "3.2"

services:
  db:
    image: mysql:5.7
    volumes:
      - .:/var/www/app
      - ./docker/db/data:/var/lib/mysql:delegated,rw
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpw
      - MYSQL_DATABASE=docker_symfony4
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - .:/var/www/app:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - 80:80

  php:
    build: 
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  composer:
    image: composer
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app